# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: N. Rajewsky Lab | Max Delbrück Center
# Description of the Site
description: Systems Biology of Gene Regulatory Elements
# URL of Image of the Site 
site-image: assets/images/lab_rensow_2022.jpg
# Keywords of the Site
site-keywords: Labpage, Academic, Lab, Webpage, MDC, Berlin, BIMSB, Biology, Open-ST, bionformatics
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: bimsb_at_night.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rajewsky@mdc-berlin.de
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: N. Rajewsky Lab
# URL for the Image of the Author
author-image: 
# 60 Words About the Author
author-about: Systems Biology of Gene Regulatory Elements
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/rajewsky-lab

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Added for generating all team member pages
collections:
  team_members:
    output: true
    permalink: "/team/:name/"

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
